#9)
nombre= input("ingrese nombre y apellido del alumno: ")
nota1= float(input("Ingrese una de las notas del alumno:"))
nota2= float(input("Ingrese una nota mas del alumno: "))
nota3= float(input("Ingrese una nota mas del alumno: "))
print("\n Nombre del alumno:", nombre, "|", "Promedio de notas:", (nota1+nota2+nota3)/3)
